# Site settings
title: Sam Eberspacher
email: sam.eberspacher@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal site of Sam Eberspacher, a software developer who currently lives in New York, NY
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samiam14.github.io" # the base hostname & protocol for your site
twitter_username: see3ya
github_username:  samiam14

# Build settings
markdown: kramdown
